version: '3'

services:
  spring-app-1:
    #image: j2eeexpert2015/demo-microservice1:latest
    image: ghcr.io/j2eeexpert2015/demo-microservice1:latest
    container_name: demo-microservice1
    build:
      context: ./demo-microservice1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  spring-app-2:
    #image: j2eeexpert2015/demo-microservice2:latest
    image: ghcr.io/j2eeexpert2015/demo-microservice2:latest
    container_name: demo-microservice2
    build:
      context: ./demo-microservice2
      dockerfile: Dockerfile
    ports:
      - "8082:8082"