version: '3'

services:
  demo-microservice1:
    image: j2eeexpert2015/demo-microservice1:latest
    container_name: demo-microservice1
    build:
      context: ./demo-microservice1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - demo-microservice2-host=demo-microservice2
      - demo-microservice2-port=8082      
  demo-microservice2:
    image: j2eeexpert2015/demo-microservice2:latest
    container_name: demo-microservice2
    build:
      context: ./demo-microservice2
      dockerfile: Dockerfile
    ports:
      - "8082:8082"