apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-microservice1
  template:
    metadata:
      labels:
        app: demo-microservice1
    spec:
      containers:
      - name: demo-microservice1-container
        image: your-registry/your-repo/your-image-name:tag
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: demo-microservice1-service
spec:
  selector:
    app: demo-microservice1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
